### ISSUE TITLE
Trojan MaxSecure

### ISSUE THREAD

**Issue by Kraleemil** [CamxxCore/RageAudioTool#2]
Virustotal flags the exe as MaxSecure trojan https://www.virustotal.com/gui/file/99f4af1b4b711f700832a4e696f53c3f43bc0f129fbc887bb55cf7a25d6f6778

**Comment by CamxxCore** [comment]
First off, the binaries are provided as a convenience. We are here on github, the project can be built from source. Secondly, with VirusTotal, you are getting a 'best guess' at if a file is malicious. Seeing one ( false ) positive from a relatively unknown (apparently shady Indian company) means nothing. You are looking for at least 50% of vendors reporting a positive to even start to consider that a file as malicious.
